version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: micro_db_autores
    ports:
      - 33665:3306
    environment:
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: kevin123
      MYSQL_DATABASE: control_laboral
      MYSQL_ROOT_PASSWORD: kevin123
  web:
    build: .
    container_name: micro_autores
    ports:
      - 8001:80
    volumes:
      - .:/opt/data
    links:
      - mysql_serve
